# Generated by Django 4.0.3 on 2022-10-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_metric_session_prediction_metricvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricvalue',
            name='metric_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metric_values', to='main_app.metric', verbose_name='Metric name'),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metric_values', to='main_app.prediction', verbose_name='Prediction'),
        ),
    ]
